apiVersion: v1
kind: Pod
metadata:
    name: hello-world-new
    labels:
        type: front-end
 
 spec:
    containers:
        - name: helloworld-container
          image: hello-world
      