apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    type: frontend
spec:
  containers:
    - name: nginx-2
      image: nginx
    - name: busy-box
      image: busybox
    

      